import type { JobSignal } from "./types";

const now = "2026-05-25T12:00:00.000Z";

export const seedSignals: JobSignal[] = [
  {
    id: "news-2026-05-25-persistent-kong-ai-control-layer",
    rank: 1,
    companyEvent: "Persistent Systems + Kong enterprise AI control-layer partnership",
    eventType: "Enterprise AI Rollout / API Governance Modernization",
    category: "AI / Cloud / Enterprise Platforms",
    secondaryCategories: ["Cyber / Compliance / Regulatory"],
    signalStrength: "High",
    eventDate: "2026-05-25",
    resourceLink: "https://www.prnewswire.com/news-releases/persistent-and-kong-announce-strategic-partnership-to-help-enterprises-securely-move-ai-into-production-302781065.html",
    sourceName: "PR Newswire",
    sector: "Enterprise AI / API platform",
    summary: "Persistent and Kong announced a strategic partnership to help enterprises move AI into production with governed API, data, and AI connectivity across hybrid and multi-cloud environments.",
    likelyJobLocations: ["Santa Clara, CA", "San Francisco Bay Area, CA", "New York, NY", "Dallas, TX", "Chicago, IL", "Atlanta, GA", "Austin, TX", "Seattle, WA", "Remote vendor delivery"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Kong and Persistent delivery work is likely to cluster around Bay Area platform teams, U.S. enterprise client hubs, cloud/API architecture groups, and global systems-integration delivery teams.",
    whyThisMayCreateContractSoftwareJobs: "Moving AI into production creates API gateway implementation, MCP and agent connectivity, data pipeline integration, policy controls, observability, PII safeguards, cloud deployment, and QA automation work.",
    likelySoftwareRoles: ["AI Engineer", "Backend Engineer", "API Integration Developer", "Python Developer", "Cloud Software Engineer", "Platform Engineer", "DevOps/SRE", "AppSec Engineer", "Data Engineer", "QA Automation/SDET", "Technical Business Analyst"],
    bestSearchKeywords: ["Persistent Kong AI integration contractor", "Kong API gateway developer contract", "enterprise AI governance API engineer", "MCP agent connectivity developer", "AI platform observability engineer contract", "API modernization contractor Kong", "GenAI platform integration developer"],
    actionPlan: "Target Kong, Persistent, API gateway, enterprise AI governance, platform engineering, and GenAI productionization contract postings across SI partners and client tech hubs.",
    confidenceNote: "High because the announcement is implementation-led and names API, data, AI governance, hybrid cloud, security, observability, and production-scale enterprise delivery.",
    watchFor: ["Kong AI Gateway implementation roles", "Persistent GenAI Hub delivery roles", "Client announcements naming Kong or Persistent", "API governance and MCP integration roles", "Hybrid-cloud AI platform modernization postings"],
    rawNotes: "Published May 25, 2026. Source says the partnership helps enterprises implement a control layer to scale AI securely and reliably across APIs, data, and AI services.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "news-2026-05-25-expertai-fincons-neuro-symbolic",
    rank: 2,
    companyEvent: "Expert.ai + Fincons partnership for neuro-symbolic AI in core business processes",
    eventType: "Enterprise AI Rollout",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "High",
    eventDate: "2026-05-25",
    resourceLink: "https://www.prnewswire.com/news-releases/expertai-and-fincons-group-join-forces-to-bring-neuro-symbolic-ai-to-data-driven-businesses-302780037.html",
    sourceName: "PR Newswire",
    sector: "Enterprise AI / Systems integration",
    summary: "Expert.ai and Fincons expanded their partnership to bring neuro-symbolic AI into enterprise business processes across financial services, insurance, media, energy, transportation, manufacturing, and public administration.",
    likelyJobLocations: ["Rockville, MD", "Washington, DC", "Northern Virginia", "New York, NY", "Boston, MA", "Chicago, IL", "Dallas, TX", "Atlanta, GA", "Remote vendor delivery"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Enterprise AI implementation work is likely around Expert.ai U.S. operations, regulated-industry clients, consulting delivery hubs, and public-sector/financial-services technology centers.",
    whyThisMayCreateContractSoftwareJobs: "Embedding AI into core processes creates workflow integration, document intelligence, data pipelines, model governance, API integration, user-facing apps, testing, and change-management software work.",
    likelySoftwareRoles: ["AI Engineer", "Python Developer", "Backend Engineer", "Full-stack Developer", "Data Engineer", "MLOps Engineer", "API Integration Developer", "QA Automation/SDET", "Business Systems Analyst", "Technical Business Analyst"],
    bestSearchKeywords: ["Expert.ai Fincons AI integration contractor", "neuro-symbolic AI developer contract", "enterprise AI workflow developer", "AI document intelligence engineer contract", "regulated enterprise AI implementation", "MLOps engineer enterprise AI contract"],
    actionPlan: "Search Expert.ai, Fincons, neuro-symbolic AI, document intelligence, regulated enterprise AI, and systems integration contract roles.",
    confidenceNote: "High because the announcement names systems integration and deployment into core business processes, which usually creates delivery, integration, and QA work.",
    watchFor: ["Named client rollouts", "Industry-specific AI workflow postings", "Document intelligence implementation roles", "Model governance and MLOps roles"],
    rawNotes: "Published May 25, 2026. Source describes a strengthened partnership combining Expert.ai AI technology with Fincons systems integration experience.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "news-2026-05-25-moonpay-chainalysis-compliance",
    rank: 3,
    companyEvent: "MoonPay recognized for compliance-first crypto payments infrastructure",
    eventType: "Stablecoin / Crypto Payments Compliance Modernization",
    category: "Banking / Payments / Fintech",
    secondaryCategories: ["Cyber / Compliance / Regulatory"],
    signalStrength: "Medium",
    eventDate: "2026-05-25",
    resourceLink: "https://www.prnewswire.com/news-releases/moonpay-wins-2026-chainalysis-innovation-award-for-compliance-302781199.html",
    sourceName: "PR Newswire",
    sector: "Crypto payments / Compliance",
    summary: "MoonPay highlighted its compliance-first crypto payments network, Chainalysis integration, real-time transaction monitoring, sanctions screening, and stablecoin infrastructure for enterprise partners.",
    likelyJobLocations: ["New York, NY", "Miami, FL", "San Francisco Bay Area, CA", "Austin, TX", "Washington, DC", "Northern Virginia", "Remote fintech delivery"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Crypto payments, compliance, licensing, and enterprise partner work often follows New York regulatory/payment hubs, fintech engineering centers, and remote platform teams.",
    whyThisMayCreateContractSoftwareJobs: "Compliance-first payments infrastructure creates transaction monitoring, sanctions screening, KYT/KYC workflows, stablecoin payment APIs, audit trails, data pipelines, and partner integration work.",
    likelySoftwareRoles: ["Payments Engineer", "Backend Engineer", "Python Developer", "Data Engineer", "API Integration Developer", "AML/KYC Systems Developer", "Fraud/Risk Systems Developer", "AppSec Engineer", "QA Automation/SDET", "Technical Business Analyst"],
    bestSearchKeywords: ["MoonPay compliance engineer contract", "crypto payments API developer contract", "stablecoin infrastructure developer", "Chainalysis integration engineer", "transaction monitoring developer contract", "sanctions screening fintech contractor", "crypto KYT KYC systems developer"],
    actionPlan: "Track MoonPay, Chainalysis, crypto payments, stablecoin infrastructure, sanctions screening, and transaction monitoring contract roles.",
    confidenceNote: "Medium because the item is an award, but the underlying platform signals compliance and payment-infrastructure buildout with real-time monitoring and enterprise partner needs.",
    watchFor: ["MoonPay enterprise partner launches", "Stablecoin payment rail integrations", "Chainalysis/KYT implementation roles", "Licensing expansion and compliance workflow roles"],
    rawNotes: "Published May 25, 2026. Source says MoonPay supports 500+ enterprise customers and powers crypto payments and stablecoin infrastructure through a single integration.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "news-2026-05-25-crypto4a-qxvault-secrets",
    rank: 4,
    companyEvent: "Crypto4A launches QxVault quantum-safe secrets management platform",
    eventType: "IAM / Secrets Management Hardening",
    category: "Cyber / Compliance / Regulatory",
    secondaryCategories: ["AI / Cloud / Enterprise Platforms"],
    signalStrength: "Medium",
    eventDate: "2026-05-25",
    resourceLink: "https://www.prnewswire.com/news-releases/crypto4a-announces-general-availability-of-qxvault-a-quantum-safe-secrets-management-platform-built-for-simplicity-sovereignty-and-scale-302780466.html",
    sourceName: "PR Newswire",
    sector: "Cybersecurity / Secrets management",
    summary: "Crypto4A announced general availability of QxVault, a quantum-safe secrets management platform for enterprise and government teams securing sensitive data across hybrid and cloud-native environments.",
    likelyJobLocations: ["Ottawa, ON", "Washington, DC", "Northern Virginia", "Maryland", "Boston, MA", "New York, NY", "San Francisco Bay Area, CA", "Remote cyber vendor delivery"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Secrets management and quantum-safe security work will likely cluster around government, federal contractor, cybersecurity, cloud, and regulated enterprise teams.",
    whyThisMayCreateContractSoftwareJobs: "Secrets management deployments create IAM integration, key management, API integration, cloud-native rollout, policy enforcement, CI/CD secret rotation, audit logging, and security testing work.",
    likelySoftwareRoles: ["IAM Engineer", "DevSecOps Engineer", "Cloud Security Engineer", "AppSec Engineer", "Platform Engineer", "Security Automation Engineer", "Python Developer", "Go Developer", "QA Automation/SDET", "Technical Business Analyst"],
    bestSearchKeywords: ["secrets management engineer contract", "quantum safe security developer", "IAM hardening contractor", "secret rotation DevSecOps contract", "cloud secrets management engineer", "FIPS cryptographic module integration", "CI/CD secrets remediation engineer"],
    actionPlan: "Search QxVault, Crypto4A, secrets management, IAM hardening, FIPS, CI/CD secret rotation, and cloud security integration postings.",
    confidenceNote: "Medium because it is a platform launch, but secrets management modernization is a concrete control implementation area with government and enterprise demand.",
    watchFor: ["Federal or regulated customer deployments", "Secrets migration projects", "IAM and key-management integration postings", "Quantum-safe security modernization roles"],
    rawNotes: "Published May 25, 2026. Source describes QxVault as a unified platform combining secrets management, cryptographic protection, and policy enforcement.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "news-2026-05-25-jotpsych-jotmeet-telehealth",
    rank: 5,
    companyEvent: "JotPsych launches integrated telehealth product connected to patient records",
    eventType: "Healthcare EHR / Workflow Modernization",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "Medium",
    eventDate: "2026-05-25",
    resourceLink: "https://www.prnewswire.com/news-releases/jotpsych-launches-jotmeet-an-integrated-telehealth-product-302779340.html",
    sourceName: "PR Newswire",
    sector: "Healthcare IT / Behavioral health",
    summary: "JotPsych launched JotMeet, integrating telehealth, recording, AI-generated notes, billing, claims, e-prescribing, scheduling, patient communications, forms, and audit intelligence into one clinical workflow.",
    likelyJobLocations: ["New York, NY", "Boston, MA", "Nashville, TN", "Atlanta, GA", "Dallas, TX", "Chicago, IL", "Philadelphia, PA", "Remote healthcare IT"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Healthcare IT work follows clinical SaaS engineering teams, behavioral-health operators, payer/provider implementation hubs, and remote healthtech delivery teams.",
    whyThisMayCreateContractSoftwareJobs: "Integrated telehealth launches create patient-record integration, video workflow, AI note generation, claims/billing integration, e-prescribing, audit intelligence, security, and QA work.",
    likelySoftwareRoles: ["Healthcare Data Engineer", "Backend Engineer", "Full-stack Developer", "API Integration Developer", "FHIR Developer", "Python Developer", "QA Automation/SDET", "Cloud Software Engineer", "Technical Business Analyst"],
    bestSearchKeywords: ["JotPsych telehealth developer contract", "behavioral health EHR integration developer", "AI clinical notes engineer contract", "healthcare billing API developer", "FHIR telehealth integration contractor", "healthcare workflow QA automation"],
    actionPlan: "Track JotPsych, behavioral health SaaS, telehealth integration, AI clinical documentation, e-prescribing, and claims workflow roles.",
    confidenceNote: "Medium because it is a product launch, but the product has multiple implementation-heavy healthcare workflow integrations.",
    watchFor: ["Provider implementation announcements", "EHR/FHIR integration roles", "AI clinical documentation postings", "Claims and billing workflow engineering roles"],
    rawNotes: "Published May 25, 2026. Source describes JotMeet as native telehealth with recording, AI notes, billing, and patient record integration.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-apple-card-chase",
    rank: 1,
    companyEvent: "Apple Card issuer transition from Goldman Sachs to Chase",
    eventType: "Issuer Transition / Card Portfolio Migration",
    category: "Banking / Payments / Fintech",
    signalStrength: "High",
    eventDate: "2026-05-01",
    resourceLink: "https://example.com/apple-card-transition",
    sourceName: "Sample news item",
    sector: "Consumer banking / Cards",
    likelyJobLocations: ["New York, NY", "Jersey City, NJ", "Wilmington, DE", "Columbus, OH", "Plano/Dallas, TX", "Charlotte, NC", "Phoenix, AZ", "Bay Area, CA", "Remote vendor delivery"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Issuer, card services, partner, payment network, and vendor delivery hubs are likely execution centers.",
    whyThisMayCreateContractSoftwareJobs: "Portfolio migration creates account conversion, API, fraud/risk, data reconciliation, QA, wallet, and customer servicing work.",
    likelySoftwareRoles: ["Java Developer", "Python Developer", "Backend Engineer", "Data Engineer", "Payments Engineer", "Card Platform Developer", "API Integration Developer", "QA Automation/SDET", "Fraud/Risk Systems Developer", "Business Systems Analyst", "Technical BA"],
    bestSearchKeywords: ["Apple Card Chase integration developer contract", "Goldman Chase Apple Card migration", "credit card portfolio migration contractor", "co-brand card platform developer", "Apple Wallet payments integration", "Chase card services Java contractor", "payments QA automation contractor"],
    actionPlan: "Search Chase, Goldman, Apple vendor, card processor, and payments integrator contract roles daily.",
    confidenceNote: "High because issuer transitions force multi-team portfolio, account, payments, and QA work.",
    rawNotes: "Sample seed signal for Apple Card-style issuer transition.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-fifth-third-comerica",
    rank: 2,
    companyEvent: "Fifth Third + Comerica bank merger example",
    eventType: "Bank Merger / System Integration",
    category: "Banking / Payments / Fintech",
    signalStrength: "High",
    eventDate: "2026-04-18",
    resourceLink: "https://example.com/bank-merger",
    sourceName: "Sample filing",
    sector: "Banking",
    likelyJobLocations: ["Cincinnati, OH", "Dallas, TX", "Charlotte, NC", "Columbus, OH", "Chicago, IL", "Remote vendor delivery"],
    workMode: "Hybrid",
    whyTheseLocations: "Bank HQs, operations hubs, conversion teams, and vendor delivery centers typically hold integration work.",
    whyThisMayCreateContractSoftwareJobs: "Bank mergers force core banking conversion, data migration, IAM consolidation, card/payment integration, reporting, and QA.",
    likelySoftwareRoles: ["Java Developer", "Data Engineer", "Backend Engineer", "API Integration Developer", "QA Automation/SDET", "Business Systems Analyst", "Technical BA"],
    bestSearchKeywords: ["Fifth Third Comerica integration developer contract", "bank merger data migration contractor", "core banking conversion Java contractor", "bank merger QA automation contract", "payments integration bank merger"],
    actionPlan: "Track core banking, branch conversion, data warehouse, risk, and digital banking job postings.",
    confidenceNote: "High because bank integrations are forced-change programs with many software workstreams.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-corporate-carveout",
    rank: 3,
    companyEvent: "Industrial software unit corporate carve-out",
    eventType: "Divestiture / TSA Exit",
    category: "M&A / Divestiture / Carve-out",
    signalStrength: "High",
    eventDate: "2026-04-04",
    resourceLink: "https://example.com/carveout",
    sourceName: "Sample press release",
    sector: "Industrial technology",
    likelyJobLocations: ["Seller HQ", "Buyer HQ", "Divested unit HQ", "Shared services centers", "Consulting hubs", "Remote vendor delivery"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Carve-outs cluster around ownership teams, shared services, ERP owners, identity teams, and consulting partners.",
    whyThisMayCreateContractSoftwareJobs: "TSA exits require system separation, tenant migration, ERP carve-out, data extraction, access controls, and testing.",
    likelySoftwareRoles: ["Data Engineer", "ETL Developer", "ERP Integration Developer", "Cloud Engineer", "DevOps/SRE", "QA Automation/SDET", "API Integration Developer", "Business Systems Analyst", "Technical BA"],
    bestSearchKeywords: ["industrial software carve-out TSA exit contractor", "system separation data engineer", "ERP carve-out developer contract", "identity tenant migration contractor", "post divestiture integration developer"],
    actionPlan: "Search divested business name, buyer/seller names, TSA exit, ERP carve-out, and system separation terms.",
    confidenceNote: "High because TSA exits create deadline-driven software separation work.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-sap-palantir-accenture",
    rank: 4,
    companyEvent: "SAP + Palantir + Accenture migration partnership",
    eventType: "ERP Modernization / Strategic Partnership",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "High",
    eventDate: "2026-03-22",
    resourceLink: "https://example.com/sap-palantir-accenture",
    sourceName: "Sample partnership announcement",
    sector: "Enterprise software",
    likelyJobLocations: ["Bay Area", "New York", "Chicago", "Atlanta", "Austin", "Remote/hybrid"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Enterprise implementation work often follows software partners, global systems integrators, and client tech hubs.",
    whyThisMayCreateContractSoftwareJobs: "ERP and data platform modernization creates integration, migration, AI governance, API, testing, and rollout work.",
    likelySoftwareRoles: ["SAP Developer", "Data Engineer", "Python Developer", "Cloud Software Engineer", "Platform Engineer", "QA Automation/SDET", "Business Systems Analyst"],
    bestSearchKeywords: ["SAP Palantir Accenture migration contractor", "SAP BTP AI integration contractor", "ERP modernization developer contract", "enterprise AI data engineer contract", "SAP data migration contractor"],
    actionPlan: "Search partner ecosystems, SAP migration roles, Palantir integration roles, and consulting delivery positions.",
    confidenceNote: "High when named enterprise platforms and implementation partners imply delivery work.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-servicenow-ai-governance",
    rank: 5,
    companyEvent: "ServiceNow AI governance rollout",
    eventType: "Enterprise AI Workflow Modernization",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "High",
    eventDate: "2026-03-12",
    resourceLink: "https://example.com/servicenow-ai-governance",
    sourceName: "Sample analyst note",
    sector: "Enterprise workflow",
    likelyJobLocations: ["Bay Area", "Chicago", "New York", "Atlanta", "Remote/hybrid"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "ServiceNow workflow programs map to enterprise platform teams and implementation partners.",
    whyThisMayCreateContractSoftwareJobs: "AI governance rollouts require workflow configuration, integrations, approvals, audit trails, and security controls.",
    likelySoftwareRoles: ["ServiceNow Developer", "AI Engineer", "Python Developer", "Data Governance Engineer", "QA Automation/SDET", "Business Systems Analyst"],
    bestSearchKeywords: ["ServiceNow AI governance developer contract", "ServiceNow GRC AI workflow contractor", "enterprise AI workflow developer", "AI governance implementation consultant", "ServiceNow platform engineer contract"],
    actionPlan: "Track ServiceNow, GRC, AI governance, workflow automation, and implementation partner postings.",
    confidenceNote: "High because governance controls turn policy into workflow and integration work.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-ransomware",
    rank: 6,
    companyEvent: "Regional manufacturer ransomware breach remediation",
    eventType: "Cyber Incident / Remediation",
    category: "Cyber / Compliance / Regulatory",
    signalStrength: "High",
    eventDate: "2026-02-27",
    resourceLink: "https://example.com/ransomware-remediation",
    sourceName: "Sample 8-K",
    sector: "Manufacturing",
    likelyJobLocations: ["Company HQ", "Affected operations centers", "Chicago", "Atlanta", "Dallas", "Remote cyber vendor delivery"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Incident response and remediation follow operations, security, legal, infrastructure, and outside cyber vendors.",
    whyThisMayCreateContractSoftwareJobs: "Ransomware recovery creates AppSec remediation, IAM hardening, logging, data recovery, CI/CD fixes, and QA work.",
    likelySoftwareRoles: ["AppSec Engineer", "DevSecOps Engineer", "IAM Engineer", "Cloud Security Engineer", "Python Developer", "Data Engineer", "QA Automation/SDET"],
    bestSearchKeywords: ["ransomware remediation engineer contract", "AppSec remediation contractor", "IAM hardening engineer contract", "incident response software engineer", "cyber remediation Python contractor"],
    actionPlan: "Search company, cyber vendors, IAM, AppSec, and remediation terms for contract openings.",
    confidenceNote: "High because cyber incidents often trigger urgent remediation budgets.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-aml-consent-order",
    rank: 7,
    companyEvent: "Consumer bank consent order AML remediation",
    eventType: "Regulatory Remediation",
    category: "Cyber / Compliance / Regulatory",
    signalStrength: "High",
    eventDate: "2026-02-19",
    resourceLink: "https://example.com/aml-consent-order",
    sourceName: "Sample consent order",
    sector: "Banking compliance",
    likelyJobLocations: ["NYC/NJ", "Charlotte", "Wilmington", "Columbus", "Dallas", "DC/Northern Virginia", "Remote cyber vendor delivery"],
    workMode: "Hybrid",
    whyTheseLocations: "AML, risk, compliance, model governance, data, and audit teams concentrate in bank risk hubs.",
    whyThisMayCreateContractSoftwareJobs: "Consent orders force AML/KYC remediation, model controls, case workflows, audit trails, reporting, and data quality work.",
    likelySoftwareRoles: ["AML/KYC Systems Developer", "Data Engineer", "Fraud/Risk Systems Developer", "Python Developer", "ServiceNow Security Developer", "GRC Automation Analyst", "QA Automation/SDET"],
    bestSearchKeywords: ["AML remediation developer contract", "consent order data engineer contractor", "KYC systems developer contract", "fraud controls engineer contract", "regulatory reporting developer"],
    actionPlan: "Search bank risk hubs, AML vendors, data quality, model governance, and GRC workflow roles.",
    confidenceNote: "High because regulator deadlines create funded remediation programs.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-guidewire",
    rank: 8,
    companyEvent: "P&C insurer Guidewire modernization",
    eventType: "Insurance Claims Platform Modernization",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "Medium",
    eventDate: "2026-01-30",
    resourceLink: "https://example.com/guidewire-modernization",
    sourceName: "Sample program note",
    sector: "Insurance",
    likelyJobLocations: ["Hartford", "NYC/NJ", "Chicago", "Dallas", "Atlanta", "Phoenix", "Des Moines", "Boston"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Insurance modernization work follows carrier HQs, claims operations, and implementation partners.",
    whyThisMayCreateContractSoftwareJobs: "Guidewire modernization creates integration, data migration, rating, claims workflow, API, and QA work.",
    likelySoftwareRoles: ["Java Developer", "Data Engineer", "API Integration Developer", "QA Automation/SDET", "Business Systems Analyst", "Technical BA"],
    bestSearchKeywords: ["Guidewire modernization developer contract", "insurance claims platform Java contractor", "Guidewire data migration contractor", "claims integration QA automation", "P&C insurance API developer contract"],
    actionPlan: "Search insurer name, Guidewire, claims migration, rating integration, and policy systems terms.",
    confidenceNote: "Medium because platform modernization is strong, but timing depends on program phase.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-healthcare-fhir",
    rank: 9,
    companyEvent: "Healthcare provider FHIR modernization",
    eventType: "Healthcare Data Interoperability",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "Medium",
    eventDate: "2026-01-18",
    resourceLink: "https://example.com/fhir-modernization",
    sourceName: "Sample provider update",
    sector: "Healthcare IT",
    likelyJobLocations: ["Nashville", "Boston", "Atlanta", "Dallas", "Chicago", "Minneapolis", "Philadelphia", "Remote healthcare IT"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Healthcare IT work follows provider HQs, EHR teams, interoperability groups, and vendor delivery teams.",
    whyThisMayCreateContractSoftwareJobs: "FHIR modernization creates API integration, data mapping, claims/EHR workflows, security, and QA needs.",
    likelySoftwareRoles: ["Backend Engineer", "Data Engineer", "API Integration Developer", "Cloud Software Engineer", "QA Automation/SDET", "Business Systems Analyst"],
    bestSearchKeywords: ["FHIR integration developer contract", "healthcare interoperability data engineer", "EHR API developer contractor", "HL7 FHIR QA automation contract", "healthcare cloud integration engineer"],
    actionPlan: "Search provider, EHR vendor, FHIR, interoperability, HL7, and claims integration roles.",
    confidenceNote: "Medium because interoperability work is durable but often phase-based.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-retail-loyalty",
    rank: 10,
    companyEvent: "National retailer loyalty and payments modernization",
    eventType: "Retail Payments / Loyalty Platform Modernization",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "Medium",
    eventDate: "2026-01-09",
    resourceLink: "https://example.com/retail-loyalty-payments",
    sourceName: "Sample retail update",
    sector: "Retail / e-commerce",
    likelyJobLocations: ["Seattle", "Atlanta", "Dallas", "Chicago", "New York", "Remote/hybrid"],
    workMode: "Remote / Hybrid",
    whyTheseLocations: "Retail platform work follows digital, e-commerce, loyalty, payment, and vendor delivery hubs.",
    whyThisMayCreateContractSoftwareJobs: "Loyalty and payment modernization creates API, mobile wallet, data platform, checkout, fraud, and QA work.",
    likelySoftwareRoles: ["Backend Engineer", "Full-stack Developer", "Data Engineer", "Payments Engineer", "QA Automation/SDET", "Business Systems Analyst"],
    bestSearchKeywords: ["retail loyalty platform developer contract", "retail payments modernization contractor", "ecommerce payments API developer", "loyalty data engineer contract", "checkout QA automation contractor"],
    actionPlan: "Search retailer, loyalty, payments, wallet, checkout, and customer data platform terms.",
    confidenceNote: "Medium because platform upgrades create work but may be spread across vendors.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-logistics-platform",
    rank: 11,
    companyEvent: "Logistics supply-chain platform modernization",
    eventType: "Supply Chain Platform Modernization",
    category: "AI / Cloud / Enterprise Platforms",
    signalStrength: "Medium",
    eventDate: "2025-12-12",
    resourceLink: "https://example.com/logistics-platform",
    sourceName: "Sample operations update",
    sector: "Logistics",
    likelyJobLocations: ["Atlanta", "Dallas", "Chicago", "Denver", "Remote/hybrid"],
    workMode: "Hybrid",
    whyTheseLocations: "Supply-chain systems follow operations hubs, control towers, warehouse tech, and integration partners.",
    whyThisMayCreateContractSoftwareJobs: "Modernization creates integration, EDI/API replacement, data pipelines, routing optimization, cloud, and QA work.",
    likelySoftwareRoles: ["Backend Engineer", "Data Engineer", "Cloud Software Engineer", "Platform Engineer", "QA Automation/SDET", "Business Systems Analyst"],
    bestSearchKeywords: ["supply chain platform modernization contractor", "logistics API integration developer", "warehouse systems data engineer contract", "TMS modernization software engineer", "EDI API replacement contractor"],
    actionPlan: "Search logistics, TMS, WMS, routing, EDI/API, and data platform roles.",
    confidenceNote: "Medium because logistics platform work is integration-heavy but company timing varies.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "seed-federal-ai-cyber",
    rank: 12,
    companyEvent: "Federal AI and cyber modernization program",
    eventType: "Government AI / Cyber Modernization",
    category: "Cyber / Compliance / Regulatory",
    signalStrength: "High",
    eventDate: "2025-11-20",
    resourceLink: "https://example.com/federal-ai-cyber",
    sourceName: "Sample award notice",
    sector: "Federal technology",
    likelyJobLocations: ["Washington DC", "Northern Virginia", "Maryland", "Huntsville, AL", "San Antonio, TX", "Colorado Springs, CO", "Tampa, FL", "St. Louis, MO"],
    workMode: "Hybrid / On-site",
    whyTheseLocations: "Federal cyber and AI programs follow agency, integrator, clearance, and mission delivery centers.",
    whyThisMayCreateContractSoftwareJobs: "AI/cyber modernization creates governance, secure software, data pipelines, IAM, audit, cloud, testing, and mission integration work.",
    likelySoftwareRoles: ["Cybersecurity Software Engineer", "AI Engineer", "Python Developer", "Data Engineer", "IAM Engineer", "Cloud Security Engineer", "QA Automation/SDET", "Technical BA"],
    bestSearchKeywords: ["federal AI cyber modernization contractor", "cleared Python AI engineer contract", "federal IAM hardening engineer", "AI governance developer federal contract", "cloud security software engineer contract"],
    actionPlan: "Search prime integrators, agency award terms, clearance filters, AI governance, and cyber modernization roles.",
    confidenceNote: "High because government modernization awards often map directly to contract staffing.",
    createdAt: now,
    updatedAt: now
  }
];
